apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: internal-pool
  namespace: metallb
spec:
  addresses:
    - 192.168.2.201-192.168.2.250
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: advert1
  namespace: metallb
spec:
  ipAddressPools:
    - internal-pool