
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: qbittorrent-ingress
  namespace: jmedia
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - qbittorrent.jacquesops.site
    - plex.jacquesops.site
    secretName: jmedia-tls
  rules:
    - host: qbittorrent.jacquesops.site
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: qbittorrent-webui
                port:
                  number: 80
    - host: plex.jacquesops.site
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: plex-web
                port:
                  number: 80
