apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: homecluster-directory-apps
  namespace: argocd
spec:
  generators:
    - list:
        elements:

          - name: argo-stack
            path: argo-stack
            namespace: default
            createNamespace: "false"

          - name: authelia
            path: authelia
            namespace: authelia
            createNamespace: "true"

          - name: gameoflife
            path: game-of-life
            namespace: gameoflife
            createNamespace: "true"

          - name: ghcr
            path: ghcr
            namespace: ghcr
            createNamespace: "false"

          - name: ingresses
            path: ingresses
            namespace: default
            createNamespace: "false"

          - name: jellyfin
            path: jellyfin
            namespace: jmedia
            createNamespace: "true"

          - name: landing
            path: landing-k8s
            namespace: jmedia
            createNamespace: "false"

          - name: pihole
            path: pihole
            namespace: pihole
            createNamespace: "true"

          - name: plex
            path: plex
            namespace: jmedia
            createNamespace: "false"

          - name: qbittorrent
            path: qbittorrent
            namespace: jmedia
            createNamespace: "false"
  template:
    metadata:
      name: "{{name}}"
    spec:
      project: default
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{namespace}}"
      source:
        repoURL: git@github.com:JacquesEhlers/homecluster.git
        targetRevision: main
        path: "{{path}}"
        directory:
          recurse: true
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace={{createNamespace}}
          - PrunePropagationPolicy=foreground
          - PruneLast=true
