apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: homecluster-helm-charts
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: argo-events
            path: argo-events
            namespace: argo-events
            valuesFile: values.yaml
            createNamespace: "true"

          - name: argo-workflows
            path: argo-workflows
            namespace: argo-workflows
            valuesFile: values.yaml
            createNamespace: "true"

          - name: cert-manager
            path: cert-manager
            namespace: cert-manager
            valuesFile: values.yaml
            createNamespace: "true"

          - name: metallb
            path: metallb
            namespace: metallb
            valuesFile: values.yaml
            createNamespace: "true"

  template:
    metadata:
      name: "{{name}}"
    spec:
      project: default
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{namespace}}"
      source:
        repoURL: git@github.com:JacquesEhlers/homecluster.git
        targetRevision: main
        path: "{{path}}"
        helm:
          valueFiles:
            - "{{valuesFile}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace={{createNamespace}}
          - PrunePropagationPolicy=foreground
          - PruneLast=true
